name: Release

# Controls when the action will run.
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    release:
        name: "Release"

        # Set up a matrix of different configurations:
        # for now Linux, MacOS and Windows
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest

        env:
            CHOOSENIM_CHOOSE_VERSION: stable
            CHOOSENIM_NO_ANALYTICS: 1

        steps:
            # Cancel other actions of the same type that might be already running

            - name: "Cancel similar actions in progress"
              uses: styfle/cancel-workflow-action@0.6.0
              with:
                  access_token: ${{ github.token }}
                  
            - name: Detect current OS
              id: os
              run: echo "::set-output name=id::${{matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'macos-latest' && 'macosx' || matrix.os == 'windows-latest' && 'windows'}}"

            # Checks out the repository
            - uses: actions/checkout@v2

            # Install libraries
            - name: install musl-gcc
              run: sudo apt-get install -y musl-tools
              if: matrix.os == 'ubuntu-latest'

            # Set path
            - name: Update $PATH
              run: echo "$HOME/.nimble/bin" >> $GITHUB_PATH
              if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'

            - name: Update %PATH%
              run: echo "${HOME}/.nimble/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
              if: matrix.os == 'windows-latest'

            # Install the compiler
            - name: Install Nim
              run: |
                  curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
                  sh init.sh -y

            # Build for linux
            - name: Build (Linux)
              run: nim c -d:release --gcc.exe:musl-gcc --gcc.linkerexe:musl-gcc --gc:orc --deepcopy:on --opt:size mn
              if: matrix.os == 'ubuntu-latest'

            # Build for MacOS
            - name: Build (MacOS, Windows)
              run: nim c -d:release --gc:orc --deepcopy:on --opt:size mn
              if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'

            - name: "Get current release"
              id: current-release
              uses: InsonusK/get-latest-release@v1.0.1
              with:
                  myToken: ${{ github.token }}
                  exclude_types: "release"
                  view_top: 1

            # Package the resulting Linux/MacOS binary
            - name: Create artifact (Linux, MacOS)
              run: zip mn_${{steps.current-release.outputs.name }}_${{steps.os.outputs.id}}_x64.zip mn
              if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
              
            # Package the resulting Windows binary
            - name: Create artifact (Windows)
              run: Compress-Archive -Path mn.exe -DestinationPath mn_v${{steps.version-win.outputs.id}}_windows_x64.zip
              if: matrix.os == 'windows-latest'

            # Upload artifacts
            - name: "Upload to release"
              uses: xresloader/upload-to-github-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  file: "mn_v*.zip"
                  overwrite: true
                  release_id: ${{steps.current-release.outputs.id }}
                  verbose: true
