name: Release

# Controls when the action will run.
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    # First, build and package our different assets
    release:
        name: "Package"

        # Set up a matrix of different configurations:
        # for now Linux, MacOS and Windows
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest

        env:
            CHOOSENIM_CHOOSE_VERSION: stable
            CHOOSENIM_NO_ANALYTICS: 1

        steps:
            # Cancel other actions of the same type that might be already running

            - name: "Cancel similar actions in progress"
              uses: styfle/cancel-workflow-action@0.6.0
              with:
                  access_token: ${{ github.token }}

            # Checks out the repository
            - uses: actions/checkout@v2

            # Install libraries
            - name: install musl-gcc
              run: sudo apt-get install -y musl-tools
              if: matrix.os == 'ubuntu-latest'

            # Set path
            - name: Update $PATH
              run: echo "$HOME/.nimble/bin" >> $GITHUB_PATH

            # Install the compiler
            - name: Install Nim
              run: |
                  curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
                  sh init.sh -y

            # Build for linux
            - name: Build (Linux)
              run: nim c -d:release --gcc.exe:musl-gcc --gcc.linkerexe:musl-gcc --gc:orc --deepcopy:on --opt:size mn
              if: matrix.os == 'ubuntu-latest'

            # Build for MacOS
            - name: Build (MacOS)
              run: nim c -d:release --gc:orc --deepcopy:on --opt:size mn
              if: matrix.os == 'macos-latest'

            # Build for Windows
            - name: Build (Windows)
              run: nim c -d:release --gc:orc --deepcopy:on --opt:size mn
              if: matrix.os == 'windows-latest'

            - name: Get Version (Linux, MacOS)
              id: version-nix
              run: echo "::set-output name=id::$(./mn mntool info:version)"
              if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'

            - name: Get Version (Windows)
              id: version-win
              run: echo "::set-output name=id::$(mn mntool info:version)"
              if: matrix.os == 'windows-latest'

            # Package the resulting Linux binary
            - name: Create artifact (Linux)
              run: |
                  install -m 0755 ./mn .
                  zip mn_v${{steps.version-nix.outputs.id}}_linux_x64.zip mn
              if: matrix.os == 'ubuntu-latest'

            # Package the resulting MacOS binary
            - name: Create artifact (MacOS)
              run: |
                  install -m 0755 ./mn .
                  zip mn_v${{steps.version-nix.outputs.id}}_macosx_x64.zip mn
              if: matrix.os == 'macosx-latest'

            # Package the resulting Windows binary
            - name: Create artifact (Windows)
              run: 7zip a -tzip mn_v${{steps.version-win.outputs.id}}_windows_x64.zip mn.exe
              if: matrix.os == 'windows-latest'

            # Upload artifacts
            - name: "Upload to release"
              uses: xresloader/upload-to-github-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  file: "mn_v*.zip"
                  update_latest_release: true
                  verbose: true
